theme: jekyll-theme-minimal
title: CIT 281- Lab 2
description: I learned to use CLI commands for directory and file manipulation, use CLI commands for git commands, how to make new a git repository, about initial JavaScript files, add file to git, ignore files, use diff to see changes, using wildcards, cloning cloud repos locally, branches, and using repo files.
